#!/bin/sh

xrdb ~/.Xresources
xset b 20 100 30
feh --bg-scale ~/Pictures/wallpapers/clouds.jpg
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 7 --transparent true --alpha 0 --tint 0x00020f --height 16 --padding 20 --distance 2 &
xsetroot -cursor_name left_ptr
pgrep dropbox || dropbox start &
pgrep nm-applet || nm-applet &
pgrep urxvtd || urxvtd -q -o -f
exec ck-launch-session dbus-launch --sh-syntax --exit-with-session /usr/bin/xmonad
